### ISSUE TITLE
buffer underrun in strtod.hpp line 565

### ISSUE THREAD

**Issue by pauldreik** [stephenberry/glaze#374]
The following test causes a buffer underrun in [strtod.hpp line 565](https://github.com/stephenberry/glaze/blob/9581fb3dee84ec5c6fcfcbcc79c4edae5915a9f3/include/glaze/util/strod.hpp#L565)

```cpp
   "buffer underrun in strod.hpp:565"_test = [] {
      std::string buffer{"000000000000000000000"};
      glz::json_t json{};
      [[maybe_unused]] auto ignored = glz::read_json(json, buffer);
   };
```

This is the offending line:

https://github.com/stephenberry/glaze/blob/9581fb3dee84ec5c6fcfcbcc79c4edae5915a9f3/include/glaze/util/strod.hpp#L564-L566

The error message is:

```
09:08:48: Starting /home/paul/code/build-glaze-clang-Debug/tests/json_test/json_test...
=================================================================
==31599==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000003f at pc 0x55b2bc3a9e20 bp 0x7fff52fbacb0 sp 0x7fff52fbaca8
READ of size 1 at 0x60300000003f thread T0
    #0 0x55b2bc3a9e1f in bool glz::detail::parse_number<double, false, unsigned char const>(double&, unsigned char const*&) /home/paul/code/glaze/include/glaze/util/strod.hpp:565:14
    #1 0x55b2bc39c180 in void glz::detail::from_json<double>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, 0u, false, false, false, false, true}, char const*&, double&, glz::context&, char const*&>(double&, glz::context&, char const*&, char const*&) /home/paul/code/glaze/include/glaze/json/read.hpp:207:25
    #2 0x55b2bc39bff4 in void glz::detail::read<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, 0u, false, false, false, false, true}, double&, glz::context&, char const*&, char const*&>(double&, glz::context&, char const*&, char const*&) /home/paul/code/glaze/include/glaze/json/read.hpp:54:16
    #3 0x55b2bc3cf40a in void glz::detail::from_json<std::variant<std::nullptr_t, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::vector<glz::json_t, std::allocator<glz::json_t> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, glz::json_t, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, glz::json_t> > > > >::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, std::variant<std::nullptr_t, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::vector<glz::json_t, std::allocator<glz::json_t> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, glz::json_t, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, glz::json_t> > > >&, glz::context&, char const*&, char const*&>(std::variant<std::nullptr_t, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::vector<glz::json_t, std::allocator<glz::json_t> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, glz::json_t, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, glz::json_t> > > >&, glz::context&, char const*&, char const*&) /home/paul/code/glaze/include/glaze/json/read.hpp:1872:22
    #4 0x55b2bc3ce17b in void glz::detail::from_json<glz::json_t>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, glz::context&, char const*&, char const*&, glz::json_t&>(glz::json_t&, glz::context&, char const*&, char const*&) /home/paul/code/glaze/include/glaze/json/read.hpp:67:13
    #5 0x55b2bc3cdf74 in void glz::detail::read<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, glz::json_t&, glz::context&, char const*&, char const*&>(glz::json_t&, glz::context&, char const*&, char const*&) /home/paul/code/glaze/include/glaze/json/read.hpp:54:16
    #6 0x55b2bc3cdb78 in glz::parse_error glz::read<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, glz::json_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&>(glz::json_t&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&) /home/paul/code/glaze/include/glaze/core/read.hpp:82:7
    #7 0x55b2bc3ccff1 in glz::parse_error glz::read_json<glz::json_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(glz::json_t&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/paul/code/glaze/include/glaze/json/read.hpp:2003:14
    #8 0x55b2bc358dd7 in $_5::operator()() const::'lambda'()::operator()() const /home/paul/code/glaze/tests/json_test/json_test.cpp:257:39
    #9 0x55b2bc358c20 in $_5::operator()() const::'lambda'()::__invoke() /home/paul/code/glaze/tests/json_test/json_test.cpp:254:46
    #10 0x55b2bc3842be in boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none>::run_impl(void (*)(), boost::ext::ut::v1_1_9::none const&) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:469:60
    #11 0x55b2bc381c83 in boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none>::operator()() /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:465:33
    #12 0x55b2bc37f429 in auto boost::ext::ut::v1_1_9::runner<boost::ext::ut::v1_1_9::reporter<boost::ext::ut::v1_1_9::printer>, 16>::on<void (*)(), boost::ext::ut::v1_1_9::none>(boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none>) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:1355:9
    #13 0x55b2bc37d97e in decltype(auto) boost::ext::ut::v1_1_9::detail::on<boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none> >(boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none>&&) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:1463:73
    #14 0x55b2bc360083 in auto boost::ext::ut::v1_1_9::detail::test::operator=<>(boost::ext::ut::v1_1_9::detail::test_location<void (*)()>) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:1486:5
    #15 0x55b2bc3587eb in $_5::operator()() const /home/paul/code/glaze/tests/json_test/json_test.cpp:254:44
    #16 0x55b2bc358460 in $_5::__invoke() /home/paul/code/glaze/tests/json_test/json_test.cpp:253:14
    #17 0x55b2bc359c16 in boost::ext::ut::v1_1_9::runner<boost::ext::ut::v1_1_9::reporter<boost::ext::ut::v1_1_9::printer>, 16>::run(boost::ext::ut::v1_1_9::run_cfg) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:1421:7
    #18 0x55b2bc352d83 in main /home/paul/code/glaze/tests/json_test/json_test.cpp:4944:41
    #19 0x7f34b14461c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #20 0x7f34b1446284 in __libc_start_main csu/../csu/libc-start.c:360:3
    #21 0x55b2bc2926d0 in _start (/home/paul/code/build-glaze-clang-Debug/tests/json_test/json_test+0x7f6d0) (BuildId: ceb9e708dd5ad43400e96c484f57f12dfe94a615)

0x60300000003f is located 1 bytes to the left of 22-byte region [0x603000000040,0x603000000056)
allocated by thread T0 here:
    #0 0x55b2bc3502ed in operator new(unsigned long) (/home/paul/code/build-glaze-clang-Debug/tests/json_test/json_test+0x13d2ed) (BuildId: ceb9e708dd5ad43400e96c484f57f12dfe94a615)
    #1 0x55b2bc361dee in std::__new_allocator<char>::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/new_allocator.h:137:27
    #2 0x55b2bc361bea in std::allocator<char>::allocate(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/allocator.h:188:32
    #3 0x55b2bc361bea in std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/alloc_traits.h:464:20
    #4 0x55b2bc36155f in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.tcc:155:14
    #5 0x55b2bc360e8c in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.tcc:225:14
    #6 0x55b2bc3603e6 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:642:2
    #7 0x55b2bc358d76 in $_5::operator()() const::'lambda'()::operator()() const /home/paul/code/glaze/tests/json_test/json_test.cpp:255:19
    #8 0x55b2bc358c20 in $_5::operator()() const::'lambda'()::__invoke() /home/paul/code/glaze/tests/json_test/json_test.cpp:254:46
    #9 0x55b2bc3842be in boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none>::run_impl(void (*)(), boost::ext::ut::v1_1_9::none const&) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:469:60
    #10 0x55b2bc381c83 in boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none>::operator()() /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:465:33
    #11 0x55b2bc37f429 in auto boost::ext::ut::v1_1_9::runner<boost::ext::ut::v1_1_9::reporter<boost::ext::ut::v1_1_9::printer>, 16>::on<void (*)(), boost::ext::ut::v1_1_9::none>(boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none>) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:1355:9
    #12 0x55b2bc37d97e in decltype(auto) boost::ext::ut::v1_1_9::detail::on<boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none> >(boost::ext::ut::v1_1_9::events::test<void (*)(), boost::ext::ut::v1_1_9::none>&&) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:1463:73
    #13 0x55b2bc360083 in auto boost::ext::ut::v1_1_9::detail::test::operator=<>(boost::ext::ut::v1_1_9::detail::test_location<void (*)()>) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:1486:5
    #14 0x55b2bc3587eb in $_5::operator()() const /home/paul/code/glaze/tests/json_test/json_test.cpp:254:44
    #15 0x55b2bc358460 in $_5::__invoke() /home/paul/code/glaze/tests/json_test/json_test.cpp:253:14
    #16 0x55b2bc359c16 in boost::ext::ut::v1_1_9::runner<boost::ext::ut::v1_1_9::reporter<boost::ext::ut::v1_1_9::printer>, 16>::run(boost::ext::ut::v1_1_9::run_cfg) /home/paul/code/build-glaze-clang-Debug/_deps/ut-src/include/boost/ut.hpp:1421:7
    #17 0x55b2bc352d83 in main /home/paul/code/glaze/tests/json_test/json_test.cpp:4944:41
    #18 0x7f34b14461c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/paul/code/glaze/include/glaze/util/strod.hpp:565:14 in bool glz::detail::parse_number<double, false, unsigned char const>(double&, unsigned char const*&)
Shadow bytes around the buggy address:
  0x0c067fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c067fff8000: fa fa 00 00 00 fa fa[fa]00 00 06 fa fa fa fa fa
  0x0c067fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==31599==ABORTING
```

**Comment by stephenberry** [comment]
Unit test added and fixed in #384
