### ISSUE TITLE
latest main crash with heap-buffer-overflow (2023-08-16)

### ISSUE THREAD

**Issue by sweihub** [stephenberry/glaze#402]
Hi @stephenberry 

I had the same crash as before, the same place, why do you insist not checking the 0 index issue? It really crashes again and again, even though it was not easy to reproduce.

The crash point: `glaze/util/dump.hpp:38:16`
```cpp
   ...

   template <char c>
   GLZ_ALWAYS_INLINE void dump(vector_like auto& b, auto&& ix) noexcept
   {
      if (ix == b.size()) [[unlikely]] {
         b.resize(b.size() * 2);
      }

      using V = std::decay_t<decltype(b[0])>;
      if constexpr (std::same_as<V, char>) {
         b[ix] = c; // <--------------------------------------  HERE, if ix or b.size() is zero????
      }
      else {
         b[ix] = static_cast<V>(c);
      }
      ++ix;
   }

  ...
```

The backtrace
```
==2967418==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x612004603641 at pc 0x560583260a6b bp 0x7f83638f3fd0 sp 0x7f83638f3fc8
WRITE of size 1 at 0x612004603641 thread T2
    #0 0x560583260a6a in void glz::detail::dump<(char)44, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&) /home/swei/quant/trade/ctp/../core/include/glaze/util/dump.hpp:38:16
    #1 0x560583426a50 in void glz::detail::write_entry_separator<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&) /home/swei/quant/trade/core/include/glaze/json/write.hpp:326:10
    #2 0x5605839ac80b in auto void glz::detail::to_json<core::QuoteData>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&)::'lambda'(auto)::operator()<std::integral_constant<unsigned long, 13ul>>(auto) const /home/swei/quant/trade/core/include/glaze/json/write.hpp:908:22
    #3 0x5605839a9d04 in auto auto glz::for_each<18ul, void glz::detail::to_json<core::QuoteData>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&)::'lambda'(auto)>(core::QuoteData&)::'lambda'(auto&&...)::operator()<std::integral_constant<unsigned long, 0ul>, std::integral_constant<unsigned long, 1ul>, std::integral_constant<unsigned long, 2ul>, std::integral_constant<unsigned long, 3ul>, std::integral_constant<unsigned long, 4ul>, std::integral_constant<unsigned long, 5ul>, std::integral_constant<unsigned long, 6ul>, std::integral_constant<unsigned long, 7ul>, std::integral_constant<unsigned long, 8ul>, std::integral_constant<unsigned long, 9ul>, std::integral_constant<unsigned long, 10ul>, std::integral_constant<unsigned long, 11ul>, std::integral_constant<unsigned long, 12ul>, std::integral_constant<unsigned long, 13ul>, std::integral_constant<unsigned long, 14ul>, std::integral_constant<unsigned long, 15ul>, std::integral_constant<unsigned long, 16ul>, std::integral_constant<unsigned long, 17ul>>(auto&&...) const /home/swei/quant/trade/core/include/glaze/util/for_each.hpp:30:47
    #4 0x5605839a98ef in decltype(auto) auto glz::indexer<void, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul, 11ul, 12ul, 13ul, 14ul, 15ul, 16ul, 17ul>(std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul, 11ul, 12ul, 13ul, 14ul, 15ul, 16ul, 17ul>)::'lambda'(auto&&)::operator()<auto glz::for_each<18ul, void glz::detail::to_json<core::QuoteData>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&)::'lambda'(auto)>(core::QuoteData&)::'lambda'(auto&&...)>(auto&&) const /home/swei/quant/trade/core/include/glaze/util/for_each.hpp:14:17
    #5 0x5605839a95b9 in auto glz::for_each<18ul, void glz::detail::to_json<core::QuoteData>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&)::'lambda'(auto)>(core::QuoteData&) /home/swei/quant/trade/core/include/glaze/util/for_each.hpp:30:14
    #6 0x5605839a93f6 in void glz::detail::to_json<core::QuoteData>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&) /home/swei/quant/trade/core/include/glaze/json/write.hpp:872:13
    #7 0x5605839a90dc in void glz::detail::write<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::QuoteData&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&) /home/swei/quant/trade/core/include/glaze/json/write.hpp:33:13
    #8 0x5605839a8123 in auto void glz::detail::to_json<core::rpc::request_t<core::QuoteData>>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&)::'lambda'(auto)::operator()<std::integral_constant<unsigned long, 3ul>>(auto) const /home/swei/quant/trade/core/include/glaze/json/write.hpp:939:19
    #9 0x5605839a7287 in auto auto glz::for_each<4ul, void glz::detail::to_json<core::rpc::request_t<core::QuoteData>>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&)::'lambda'(auto)>(core::rpc::request_t<core::QuoteData>&)::'lambda'(auto&&...)::operator()<std::integral_constant<unsigned long, 0ul>, std::integral_constant<unsigned long, 1ul>, std::integral_constant<unsigned long, 2ul>, std::integral_constant<unsigned long, 3ul>>(auto&&...) const /home/swei/quant/trade/core/include/glaze/util/for_each.hpp:30:47
    #10 0x5605839a7128 in decltype(auto) auto glz::indexer<void, 0ul, 1ul, 2ul, 3ul>(std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul>)::'lambda'(auto&&)::operator()<auto glz::for_each<4ul, void glz::detail::to_json<core::rpc::request_t<core::QuoteData>>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&)::'lambda'(auto)>(core::rpc::request_t<core::QuoteData>&)::'lambda'(auto&&...)>(auto&&) const /home/swei/quant/trade/core/include/glaze/util/for_each.hpp:14:17
    #11 0x5605839a6fa9 in auto glz::for_each<4ul, void glz::detail::to_json<core::rpc::request_t<core::QuoteData>>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&)::'lambda'(auto)>(core::rpc::request_t<core::QuoteData>&) /home/swei/quant/trade/core/include/glaze/util/for_each.hpp:30:14
    #12 0x5605839a6de6 in void glz::detail::to_json<core::rpc::request_t<core::QuoteData>>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&) /home/swei/quant/trade/core/include/glaze/json/write.hpp:872:13
    #13 0x5605839a6b3c in void glz::detail::write<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&>(core::rpc::request_t<core::QuoteData>&, glz::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, unsigned long&) /home/swei/quant/trade/core/include/glaze/json/write.hpp:33:13
    #14 0x5605839a6a61 in void glz::write<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::rpc::request_t<core::QuoteData>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, glz::context&>(core::rpc::request_t<core::QuoteData>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, glz::context&) /home/swei/quant/trade/core/include/glaze/core/write.hpp:40:7
    #15 0x5605839a68ab in void glz::write<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true}, core::rpc::request_t<core::QuoteData>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>(core::rpc::request_t<core::QuoteData>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) /home/swei/quant/trade/core/include/glaze/core/write.hpp:50:7
    #16 0x56058399f97c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>& json::write<core::rpc::request_t<core::QuoteData>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>(core::rpc::request_t<core::QuoteData>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) /home/swei/quant/trade/core/include/core/json.hpp:86:5
    #17 0x560583999116 in DataHub::send_quote(core::Pod&) /home/swei/quant/trade/core/src/datahub.cpp:222:5
    #18 0x560583998eac in DataHub::process(core::Pod&) /home/swei/quant/trade/core/src/datahub.cpp:185:9
    #19 0x560583998c29 in DataHub::main() /home/swei/quant/trade/core/src/datahub.cpp:167:13
...
```

**Comment by stephenberry** [comment]
@sweihub I'm sorry for this bug you're seeing. The reason I haven't made your fix is that this may be indicative of a deeper issue that I'd like to fix, and if I just throw on this change then it could hide a deeper problem.

Nevertheless, it's important to fix this issue. So, let's dive in. It seems like this is only an issue when `b.size()` is zero. The problem is that we resize to zero when `b.size()` is zero. If `ix == b.size()`, then the buffer will grow as long as it isn't zero, so we won't access out of bounds.

In your stack trace above, `#14` calls line 40 of `glaze/core/write.hpp`. Just before this line is the following code:
```c++
if constexpr (detail::resizeable<Buffer>) {
   if (buffer.empty()) {
      buffer.resize(128);
   }
}
```

I verified `static_assert(detail::resizeable<std::string&>)` passes, so the buffer you are using should be getting resized.

So, as long as your Buffer is resizable, then it should never be zero. This is what is confusing me, because somewhere further along the stack trace the buffer must be getting cleared??? This would be a big issue for writing out JSON, because it would mean we are clearing what we've written to the buffer. Hence, why I say this could be indicative of a more serious problem. You don't have any custom writing that would be clearing the buffer, do you?

Because resizing is not too common, I'm thinking of making the following change that should fix your problem:
```c++
if (ix == b.size()) [[unlikely]] {
   b.resize((std::max)(b.size() * 2, 128));
}
```

I prefer multiples of 2 for buffer alignment. I'm pretty sure this will fix your issue, but as a warning, I think your issue is probably indicative of a deeper problem, which may not even be due to glaze.

**Comment by sweihub** [comment]
Hi Mr. @stephenberry 

I get your point, this is insane, we must dig it out. However, I did not do anything fancy as we discussed in previous thread: 
https://github.com/stephenberry/glaze/issues/297,  the related code wasn't changed, I post again for convenience.

The possible crash conditons are two
1. if both `ix` and `b.size()` are zeroes?
2. if `ix > b.size()` already? If zero buffer is imposible, should be this?

I just called the wrapped `json::write` to serialize into JSON string.

**The compiler I used**
```
❯ clang++ --version
Ubuntu clang version 16.0.6 (++20230704084245+7cbf1a259152-1~exp1~20230704204333.104)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**The compile flags**
```
/usr/bin/clang++  -I/home/swei/quant/trade/core/include -std=c++20 -Wall \
-DLLVM_USE_LINKER=lld \
-Wno-missing-braces \
-Wno-unused-local-typedef \
-fsanitize=address \
-fno-omit-frame-pointer -g -DDEBUG -g -DGTEST_HAS_PTHREAD=1
```
**The wrapped code**
```cpp
#pragma once

#include <glaze/glaze.hpp>

namespace json {

template <class T>
inline int read_file(T &value, std::string const &filename)
{
    using namespace glz;

    std::string buffer;
    context ctx{.current_file = filename};
    std::filesystem::path path{filename};

    constexpr auto options = glz::opts{
        .error_on_unknown_keys = false,
        .error_on_missing_keys = false,
    };

    try {
        auto n = file_to_buffer(buffer, ctx.current_file);
        if (n != error_code::none) {
            return (int)n;
        }
        auto ret = glz::read<options>(value, buffer, ctx);
        return (int)ret.ec;
    } catch (...) {
    }

    return (-1);
}

template <class T>
inline int write_file(T &value, std::string const &filename)
{
    using namespace glz;

    std::string buffer;
    std::ofstream file(filename);
    context ctx{.current_file = filename};
    constexpr auto options = opts{.prettify = true, .indentation_width = 2};

    try {
        write<options>(value, buffer, ctx);
        if (file) {
            file << buffer;
        } else {
            return -1;
        }
    } catch (...) {
        return -2;
    }

    return 0;
}

// Deserialize from string
template <class T, class Buffer>
inline int read(T &value, Buffer &&buffer) noexcept
{
    constexpr auto options = glz::opts{
        .error_on_unknown_keys = false,
        .error_on_missing_keys = false,
    };

    try {
        auto ret = glz::read<options>(value, std::forward<Buffer>(buffer));
        return (int)ret.ec;
    } catch (...) {
    }

    return (-1);
}

// Serialize into string
template <class T>
inline auto write(T &&value)
{
    return glz::write_json(value);
}

template <class T, class Buffer>
inline Buffer &write(T &value, Buffer &buffer)
{
    glz::write<glz::opts{}>(value, buffer);
    return buffer;
}

template <class T>
inline auto prettify(T &&value)
{
    std::string buffer{};
    glz::write<glz::opts{.prettify = true, .indentation_width = 2}>(std::forward<T>(value), buffer);
    return buffer;
}

// Get a JSON value
template <class T, glz::string_literal Str>
inline T get(glz::detail::contiguous auto &&buffer, std::string *error = nullptr) noexcept
{
    try {
        auto ret = glz::get_as_json<T, Str>(buffer);
        if (ret.has_value()) {
            return ret.value();
        }
    } catch (std::runtime_error &e) {
        if (error)
            *error = e.what();
    } catch (...) {
        if (error)
            *error = "unkown error";
    }

    return T{};
}
} // namespace json

```

**Comment by stephenberry** [comment]
@sweihub, thanks for sharing the related code again. I just merged in #403, which does the safer resize check, so I think this should fix your problem. I'm continuing to dig and see if something else is going on.

The case `ix > b.size()` should be impossible, and is indicative of another problem if it happens. So, please let me know if this ever shows up. But, `b.size() == 0` should not be an issue anymore.

**Comment by sweihub** [comment]
Hi @stephenberry 

I just checked your commit, why do you limit max size to 128? If the `ix` really exceeds 128?
```cpp
b.resize((std::max)(b.size() * 2, size_t{128}));
```

**Comment by stephenberry** [comment]
@sweihub, Many thanks, that dumb mistake. I reverted.

**Comment by stephenberry** [comment]
@sweihub I just pushed a proper fix with #404, again thanks so much

**Comment by sweihub** [comment]
Now it makes sense, however, any possibility that `ix > b.size()` again?  `>=` operator will  stop this issue.
```diff
    if (ix == b.size()) [[unlikely]] {
-        b.resize(b.size() * 2);
+        b.resize(b.size() == 0 ? 128 : b.size() * 2);
      }
```

BTW, the fix line can be this way for perfectionist
```diff
-    if (ix == b.size()) [[unlikely]] {
+    if (ix >= b.size()) [[unlikely]] {
-        b.resize(b.size() * 2);
+        b.resize(b.size() * 2 + 128*b.empty());
      }
```

**Comment by stephenberry** [comment]
Using >= vs == is a performance loss, but because it's on an unlikely branch it is likely immaterial. I will benchmark and get back to you on this.

**Comment by sweihub** [comment]
OK, I like the way you pursue performance, I think the assemblies are single instructions: `JE`, `JGE`, `JL`, ...

https://en.wikibooks.org/wiki/X86_Disassembly/Branches

The modern compiler will handle that. Let's see your result, thanks!

**Comment by stephenberry** [comment]
@sweihub 
I've been thinking about the case where `ix > b.size()` more and have a few thoughts. If this case happens, then we must have already written past the end of our buffer. This is a problem that should never happen, but it is definitely an error if it does. So, I don't want to add `ix >= b.size()` just to appease the address sanitizer, because the address sanitizer is pointing out a legitimate error. If we hide this error from the address sanitizer then we are in a worse place, because now we don't know that we are writing out of buffer bounds.

I would expect the address sanitizer to pop up the error sooner if we ever had `ix > b.size()`, so I don't think this is actually an issue. So, I think it's best to address these issues where they happen to prevent illegal writing rather than after they happen.

Hope all that makes sense. And, let me know if you have counter arguments. Thanks!

**Comment by sweihub** [comment]
Hey Stephen

Your explanation makes sense, I’ll keep an eye on it. 

Thank you very much!
