### ISSUE TITLE
UndefinedBehaviourSanitizer: load of misaligned address

### ISSUE THREAD

**Issue by Oipo** [stephenberry/glaze#611]
Compiling and running the following program leads to a couple of UB sanitizer reports. Not sure if I'm doing something wrong or if there's an issue in glaze. On x86 this might not be an issue, but I'm also targeting aarch64, which does not allow loading misaligned addresses, or at least, you will lose atomicity at the CPU level.

```c++
#include <glaze.hpp>
#include <optional>
#include <string>
#include <vector>

struct EtcdKvReply final {
    std::vector<std::string> read;
    std::vector<std::string> write;
};

struct EtcdPermissionsReply final {
    EtcdKvReply kv;
};

struct EtcdRoleReply final {
    std::string role;
    EtcdPermissionsReply permissions;
};

struct EtcdUserReply final {
    std::string user;
    std::optional<std::string> password;
    std::vector<EtcdRoleReply> roles;
};



template <>
struct glz::meta<EtcdKvReply> {
    using T = EtcdKvReply;
    static constexpr auto value = object(
            "read", &T::read,
            "write", &T::write
    );
};

template <>
struct glz::meta<EtcdPermissionsReply> {
    using T = EtcdPermissionsReply;
    static constexpr auto value = object(
            "kv", &T::kv
    );
};

template <>
struct glz::meta<EtcdRoleReply> {
    using T = EtcdRoleReply;
    static constexpr auto value = object(
            "role", &T::role,
            "permissions", &T::permissions
    );
};

template <>
struct glz::meta<EtcdUserReply> {
    using T = EtcdUserReply;
    static constexpr auto value = object(
            "user", &T::user,
            "password", &T::password,
            "roles", &T::roles
    );
};

int main() {
  std::string json = "{\"users\":[{\"user\":\"root\",\"roles\":[{\"role\":\"root\",\"permissions\":{\"kv\":{\"read\":[\"/*\"],\"write\":[\"/*\"]}}}]}]}";

  EtcdUserReply user_create{};
  user_create.user = "test_user";
  user_create.password = "test_user";
  std::vector<uint8_t> buf;
  glz::write_json(user_create, buf);

  return 0;
}

```

```shell
oipo@oipo-X670E-AORUS-MASTER:~/Programming/Ichor/external/glaze$ g++ -std=c++20 -fsanitize=undefined -I./include test.cpp
oipo@oipo-X670E-AORUS-MASTER:~/Programming/Ichor/external/glaze$ ./a.out 
include/glaze/json/write.hpp:313:65: runtime error: load of misaligned address 0x0000007c6339 for type 'long unsigned int', which requires 8 byte alignment
0x0000007c6339: note: pointer points here
 72 22 3a  22 74 65 73 74 5f 75 73  65 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^ 
    #0 0x40b6b8 in void glz::detail::to_json<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, std::vector<unsigned char, std::allocator<unsigned char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40b6b8)
    #1 0x40a1b7 in void glz::detail::write<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40a1b7)
    #2 0x4088c2 in auto glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}::operator()<std::integral_constant<unsigned long, 0ul> >(std::integral_constant<unsigned long, 0ul>) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4088c2)
    #3 0x4094ff in auto glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}::operator()<std::integral_constant<unsigned long, 0ul>, std::integral_constant<unsigned long, 1ul>, std::integral_constant<unsigned long, 2ul> >(std::integral_constant<unsigned long, 0ul>&&, std::integral_constant<unsigned long, 1ul>&&, std::integral_constant<unsigned long, 2ul>&&) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4094ff)
    #4 0x4082c8 in decltype(auto) glz::indexer<void, 0ul, 1ul, 2ul>(std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>)::{lambda(auto:1&&)#1}::operator()<glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}>(glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}&&) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4082c8)
    #5 0x4096c4 in auto glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4096c4)
    #6 0x40974f in void glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40974f)
    #7 0x407d9b in void glz::detail::to_json<EtcdUserReply>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x407d9b)
    #8 0x4067dc in void glz::detail::write<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4067dc)
    #9 0x405a49 in void glz::write<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >, glz::context&>(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&, glz::context&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x405a49)
    #10 0x40501d in void glz::write<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> > >(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40501d)
    #11 0x403f18 in auto glz::write_json<EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&>(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x403f18)
    #12 0x40233f in main (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40233f)
    #13 0x7fe8c6c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x7fe8c6c29e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #15 0x4021d4 in _start (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4021d4)

include/glaze/json/write.hpp:313:86: runtime error: load of misaligned address 0x0000007c6339 for type 'long unsigned int', which requires 8 byte alignment
0x0000007c6339: note: pointer points here
 72 22 3a  22 74 65 73 74 5f 75 73  65 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^ 
    #0 0x40b6ed in void glz::detail::to_json<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, std::vector<unsigned char, std::allocator<unsigned char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40b6ed)
    #1 0x40a1b7 in void glz::detail::write<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40a1b7)
    #2 0x4088c2 in auto glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}::operator()<std::integral_constant<unsigned long, 0ul> >(std::integral_constant<unsigned long, 0ul>) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4088c2)
    #3 0x4094ff in auto glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}::operator()<std::integral_constant<unsigned long, 0ul>, std::integral_constant<unsigned long, 1ul>, std::integral_constant<unsigned long, 2ul> >(std::integral_constant<unsigned long, 0ul>&&, std::integral_constant<unsigned long, 1ul>&&, std::integral_constant<unsigned long, 2ul>&&) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4094ff)
    #4 0x4082c8 in decltype(auto) glz::indexer<void, 0ul, 1ul, 2ul>(std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>)::{lambda(auto:1&&)#1}::operator()<glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}>(glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}&&) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4082c8)
    #5 0x4096c4 in auto glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4096c4)
    #6 0x40974f in void glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40974f)
    #7 0x407d9b in void glz::detail::to_json<EtcdUserReply>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x407d9b)
    #8 0x4067dc in void glz::detail::write<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4067dc)
    #9 0x405a49 in void glz::write<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >, glz::context&>(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&, glz::context&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x405a49)
    #10 0x40501d in void glz::write<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> > >(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40501d)
    #11 0x403f18 in auto glz::write_json<EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&>(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x403f18)
    #12 0x40233f in main (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40233f)
    #13 0x7fe8c6c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x7fe8c6c29e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #15 0x4021d4 in _start (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4021d4)

include/glaze/json/write.hpp:313:107: runtime error: load of misaligned address 0x0000007c6339 for type 'long unsigned int', which requires 8 byte alignment
0x0000007c6339: note: pointer points here
 72 22 3a  22 74 65 73 74 5f 75 73  65 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^ 
    #0 0x40b722 in void glz::detail::to_json<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, std::vector<unsigned char, std::allocator<unsigned char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40b722)
    #1 0x40a1b7 in void glz::detail::write<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40a1b7)
    #2 0x4088c2 in auto glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}::operator()<std::integral_constant<unsigned long, 0ul> >(std::integral_constant<unsigned long, 0ul>) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4088c2)
    #3 0x4094ff in auto glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}::operator()<std::integral_constant<unsigned long, 0ul>, std::integral_constant<unsigned long, 1ul>, std::integral_constant<unsigned long, 2ul> >(std::integral_constant<unsigned long, 0ul>&&, std::integral_constant<unsigned long, 1ul>&&, std::integral_constant<unsigned long, 2ul>&&) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4094ff)
    #4 0x4082c8 in decltype(auto) glz::indexer<void, 0ul, 1ul, 2ul>(std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>)::{lambda(auto:1&&)#1}::operator()<glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}>(glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&)::{lambda((auto:1&&)...)#1}&&) const (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4082c8)
    #5 0x4096c4 in auto glz::for_each<3ul, glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)::{lambda(auto:1)#1}>(EtcdUserReply&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4096c4)
    #6 0x40974f in void glz::detail::to_json<EtcdUserReply>::op_base<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40974f)
    #7 0x407d9b in void glz::detail::to_json<EtcdUserReply>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x407d9b)
    #8 0x4067dc in void glz::detail::write<10u>::op<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&>(EtcdUserReply&, glz::context&, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4067dc)
    #9 0x405a49 in void glz::write<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >, glz::context&>(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&, glz::context&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x405a49)
    #10 0x40501d in void glz::write<glz::opts{10u, false, true, true, true, false, (char)32, (unsigned char)3, false, true, false, false, false, 0u, false, false, false, false, false, false, false, false, true}, EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> > >(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40501d)
    #11 0x403f18 in auto glz::write_json<EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&>(EtcdUserReply&, std::vector<unsigned char, std::allocator<unsigned char> >&) (/home/oipo/Programming/Ichor/external/glaze/a.out+0x403f18)
    #12 0x40233f in main (/home/oipo/Programming/Ichor/external/glaze/a.out+0x40233f)
    #13 0x7fe8c6c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x7fe8c6c29e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #15 0x4021d4 in _start (/home/oipo/Programming/Ichor/external/glaze/a.out+0x4021d4)

```

GCC version:
```shell
oipo@oipo-X670E-AORUS-MASTER:~/Programming/Ichor/external/glaze$ g++-11 -v
Using built-in specs.
COLLECT_GCC=g++-11
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
```

But I also tested on gcc version 13.1.1 20230611 [master r13-6340-g4341106354c] and get the same results

**Comment by stephenberry** [comment]
Thanks for pointing this out! I just merged a fix #613

**Comment by Oipo** [comment]
Super, thanks!
